swapiURL:
  planets: https://swapi.dev/api/planets
  people: https://swapi.dev/api/people
  starships: https://swapi.dev/api/starships/

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: false


